# Generated by Django 4.0.3 on 2022-04-12 01:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='property_state',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='zip_code',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
