# Generated by Django 4.0.3 on 2022-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quote_property_state_quote_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_number',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
