# Generated by Django 4.0.3 on 2022-04-12 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_quote_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='property_owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
