# Generated by Django 4.0.3 on 2022-04-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_property_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='property_owner',
            new_name='name',
        ),
    ]
